apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: release-metrics-secrets
  namespace: release-metrics
spec:
  targetNamespace: release-metrics
  interval: 10m
  decryption:
    provider: sops
    secretRef:
      name: tenant-sops-gpg
  sourceRef:
    kind: GitRepository
    name: release-metrics-exporters
    namespace: flux-system
  path: "./secrets"
  prune: true
