apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-metrics-exporters
  namespace: release-metrics
spec:
  chart:
    spec:
      chart: release-metrics-exporters
      version: "0.0.6"
      sourceRef:
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      interval: 1m
  interval: 1m
  values:
    github:
      listenPort: 9888
      metricsPath: /metrics
      repos:
      - filecoin-project/lotus
    dockerhub:
      listenPort: 9888
      metricsPath: /metrics
      images:
      - filecoin/lotus
      - filecoin/lotus-all-in-one
      - filecoin/lotus-test
    homebrew:
      listenPort: 9888
      metricsPath: /metrics
      formulae:
      - filecoin-project/lotus/lotus
    snapcraft:
      listenPort: 9888
      metricsPath: /metrics
      names:
      # ids can be found at https://dashboard.snapcraft.io/snaps/<SNAP_NAME>/
      - lotus  # id: NJBwi12Vq8X2ygw2FoJWnhvYYhQlRhuT
      - lotus-filecoin  # id: 1vzTBhup6bI9eocqFz93rMQjrC2qQvbg
